name = "custom-wall"

[[rows]]
  [[rows.screens]]
    bezel = 2.75
    height = 9
    id = "pi-wall-tv-0"
    width = 12

  [[rows.screens]]
    bezel = 1
    height = 5.75
    id = "pi-wall-tv-1"
    width = 7.75
