name = "custom-wall"

[[rows]]
  [[rows.screens]]
    bezel = 1.75
    height = 16.5
    id = "pi-wall-tv-1"
    width = 22.25

  [[rows.screens]]
    bezel = 2
    height = 16.5
    id = "pi-wall-tv-2"
    width = 22.25

[[rows]]
  [[rows.screens]]
    bezel = 1
    height = 22
    id = "pi-wall-tv-3"
    width = 22
  [[rows.screens]]
    bezel = 1
    height = 22
    id = "pi-wall-tv-4"
    width = 22
