layout = "main-horizontal"
name = "pi-wall-demo"
pane_name_user_option = "custom_pane_title"
start_directory = "$HOME"

[[windows]]
  layout = "tiled"
  name = "server"

  [[windows.panes]]
  commands = ["ffmpeg -re -i test.mp4 -vcodec copy -f avi -an \"udp://239.0.1.23:1234\""]

[[windows]]
  layout = "tiled"
  name = "client-one"

  [[windows.panes]]
  commands = ["pwomxplayer --config custom-wall_config --tile-code pi-wall-tv-1 udp://239.0.1.23:1234?buffer_size=1200000B"]

[[windows]]
  layout = "tiled"
  name = "client-two"

  [[windows.panes]]
  commands = ["pwomxplayer --config custom-wall_config --tile-code pi-wall-tv-2 udp://239.0.1.23:1234?buffer_size=1200000B"]
